// 定义语言数据
const languages = {
	"zh-Hant": {
		"company-name": "胖橘文化有限公司",
		"nav-home": "首頁",
		"nav-mission": "經營理念",
		"nav-business": "主營業務",
		"nav-contact": "聯繫我們",
		"hero-title": "胖橘文化<br>TRPG體驗平台",
		"hero-desc": "探索奇幻世界，釋放想像力，建立真摯連結",
		"hero-btn-1": "立即體驗",
		"hero-btn-2": "了解更多",
		"home-company-title": "公司簡介",
		"home-company-desc": "胖橘文化有限公司成立於2025年，旨在為生活緊湊的現代人減緩壓力、並在遊戲世界重新燃起生命力。",
		"home-company-desc2": "我們擅長策劃各種TRPG主題活動，創造一個放鬆、有趣、富有想像力的空間，讓人們在體驗不同的角色和故事同時，看見人生的諸多可能性。",
		"home-stats-1": "活躍用戶",
		"home-stats-2": "活動舉辦",
		"home-stats-3": "滿意度",
		"home-events-title": "最新活動",
		"home-events-more": "查看全部",
		"event-tag-new": "新活動",
		"event-1-title": "TRPG在新竹",
		"event-1-desc": "在新竹地區固定舉辦的新手推廣活動，也歡迎TRPG愛好者們一起同樂。",
		"event-register": "立即報名",
		"event-tag-featured": "精選",
		"event-2-title": "專場活動",
		"event-2-desc": "喜歡⚔️劍與魔法🔥世界的朋友，歡迎一起來體驗桌上角色扮演遊戲的魅力！",
		"event-tag-popular": "熱門",
		"event-3-title": "同學們的TRPG",
		"event-3-desc": "專為各位同學們，打造了一場獨特的TRPG跑團活動，讓奇幻世界的精彩旅程，為大家舒緩生活壓力、帶來迎戰課業與未來的勇氣。",
		"home-partners": "合作夥伴",
		"partners1": "老獅的藏寶庫",
		"partners2": "醫院也瘋狂",
		"partners3": "謎寶空間",
		"mission-title": "經營理念",
		"mission-desc": "我們將通過TRPG創造連結，幫助充滿壓力的現代人，重新獲得對生活的動力和憧憬。",
		"mission-1-title": "關懷現代人",
		"mission-1-desc": "沉浸感強烈的TRPG遊戲，有助於緩解當下人們來自學習、工作、和生活的壓力，重新找回生活節奏",
		"mission-2-title": "活絡社群",
		"mission-2-desc": "我們致力於讓喜愛玩遊戲的朋友，能藉由玩TRPG參與聚會和活動，更加強化人與人之間的交流。",
		"mission-3-title": "創新發展",
		"mission-3-desc": "透過結合文化、教育、商業三者，我們將為客戶提供全新的桌上角色扮演活動形式和獨特體驗。",
		"mission-4-title": "合作共贏",
		"mission-4-desc": "為了推動TRPG文化的發展，我們將與企業、學校、社區建立長期合作關係，以期創造對多方有利的局面。",
		"stats-users": "活躍用戶",
		"stats-events": "活動舉辦",
		"stats-cities": "合作城市",
		"stats-satisfaction": "客戶滿意度",
		"business-title": "主營業務",
		"business-desc": "從線下活動規劃，到影視配音服務，我們提供多種以TRPG為主題的服務項目，並可為客戶量身訂做專屬的解決方案",
		"business-1-title": "TRPG活動規劃",
		"business-1-sub1": "企業團體活動",
		"business-1-sub1-desc": "善用TRPG強互動性的特點，在玩遊戲的同時，可以有效提升同仁間的溝通效率及團隊向心力，使公司整體士氣提升。",
		"business-1-sub2": "學校營隊活動",
		"business-1-sub2-desc": "將教育課程與TRPG遊戲方式結合，並通過營隊方式呈現，讓學生在充滿趣味的遊戲過程中培養想像力、邏輯思維及社交技巧。",
		"business-2-title": "影視廣告配音",
		"business-2-sub1": "影視作品配音",
		"business-2-sub1-desc": "為電影、電視劇、動畫等影視作品提供專業配音服務，包括角色配音、旁白配音，並根據作品需求配合調整。",
		"business-2-sub2": "商業廣告配音",
		"business-2-sub2-desc": "為企業廣告、產品宣傳片、企業形象片等提供配音服務，根據不同的風格和需求，選擇合適的配音表現方式。",
		"business-3-title": "文創品牌經營",
		"business-3-sub1": "穀子小物製作",
		"business-3-sub1-desc": "協助客戶製作其自有品牌的周邊產品，並可根據品牌需求，協助設計對應的產品行銷策略。",
		"business-3-sub2": "正版商品販售",
		"business-3-sub2-desc": "與知名IP合作，獨家販售正版授權的穀子套組，並同時提供線下及線上商店販售通路。",
		"business-4-title": "教育與培訓",
		"business-4-sub1": "專業主持培訓",
		"business-4-sub1-desc": "以講座、課程及團務實戰的方式，持續培養專業TRPG主持人，讓桌上角色扮演的火種得以遍地開花。",
		"business-4-sub2": "劇本創作指導",
		"business-4-sub2-desc": "為TRPG愛好者和從業者提供劇本創作指導，除了提升故事深度，也能因應教育或業界需求，設計獨特的遊戲內涵。",
		"contact-title": "聯絡我們",
		"contact-desc": "如果您有任何問題或合作意向，請隨時聯絡我們。",
		"contact-info": "聯絡資訊",
		"contact-address-title": "地址",
		"contact-address": "新竹市東區",
		<!-- "contact-phone": "電話：[公司電話]", -->
		"contact-email-title": "電子郵件",
		"contact-email": "lionstrpgvault@gmail.com",
		"contact-hours-title": "營業時間",
		"contact-hours": "10:00-20:00",
		"contact-follow": "關注我們",
		"contact-link": "點擊下方按鈕獲取活動最新資訊，商務合作請洽詢FB粉專",
		"footer-company":"胖橘文化有限公司",
		"footer-desc":"本公司以TRPG為核心，提供企業及學校活動規劃、影視配音等多元化服務，幫助現代人減輕壓力、增進交流。",
		"footer-quicklinks":"快速連結",
		"footer-home":"首頁",
		"footer-mission":"經營理念",
		"footer-business":"主營業務",
		"footer-contact":"聯繫我們",
		"footer-services":"服務項目",
		"footer-service-1":"TRPG活動企劃",
		"footer-service-2":"影視廣告配音",
		"footer-service-3":"文化體驗服務",
		"footer-service-4":"培訓與指導",
		"footer-address":"TRPG活動企劃",
		"footer-email":"lionstrpgvault@gmail.com",
		"footer-hours":"10:00-20:00"				
	},
	"zh-Hans": {
		"company-name": "胖橘文化有限公司",
		"nav-home": "首页",
		"nav-mission": "经营理念",
		"nav-business": "主营业务",
		"nav-contact": "联系我们",
		"hero-title": "胖橘文化<br>TRPG体验平台",
		"hero-desc": "探索奇幻世界，释放想象力，建立真挚连接",
		"hero-btn-1": "立即体验",
		"hero-btn-2": "了解更多",
		"home-company-title": "公司简介",
		"home-company-desc": "胖橘文化有限公司成立于2025年，旨在为生活紧凑的现代人减缓压力、并在游戏世界重新燃起生命力。",
		"home-company-desc2": "我们擅长策划各种TRPG主题活动，创造一个放松、有趣、富有想象力的空间，让人们在体验不同的角色和故事同时，看见人生的诸多可能性。",
		"home-stats-1": "活跃用户",
		"home-stats-2": "活动举办",
		"home-stats-3": "满意度",
		"home-events-title": "最新活动",
		"home-events-more": "查看全部",
		"event-tag-new": "新活动",
		"event-1-title": "TRPG在新竹",
		"event-1-desc": "在新竹地区固定举办的新手推广活动，也欢迎TRPG爱好者们一起同乐。",
		"event-register": "立即报名",
		"event-tag-featured": "精选",
		"event-2-title": "专场活动",
		"event-2-desc": "喜欢⚔️剑与魔法🔥世界的朋友，欢迎一起来体验桌上角色扮演游戏的魅力！",
		"event-tag-popular": "热门",
		"event-3-title": "同学们的TRPG",
		"event-3-desc": "专为各位同学们，打造了一场独特的TRPG跑团活动，让奇幻世界的精彩旅程，为大家舒缓生活压力，带来迎战课业与未来的勇气。",
		"home-partners": "合作伙伴",
		"partners1": "老狮的藏宝库",
		"partners2": "医院也疯狂",
		"partners3": "谜宝空间",
		"mission-title": "经营理念",
		"mission-desc": "我们将通过TRPG创造连接，帮助充满压力的现代人，重新获得对生活的动力和憧憬。",
		"mission-1-title": "关怀现代人",
		"mission-1-desc": "沉浸感强烈的TRPG游戏，有助于缓解当下人们来自学习、工作、和生活的压力，重新找回生活节奏",
		"mission-2-title": "活络社群",
		"mission-2-desc": "我们致力于让喜爱玩游戏的朋友，能借由玩TRPG参与聚会和活动，更加强化人与人之间的交流。",
		"mission-3-title": "创新发展",
		"mission-3-desc": "透过结合文化、教育、商业三者，我们将为客户提供全新的桌上角色扮演活动形式和独特体验。",
		"mission-4-title": "合作共赢",
		"mission-4-desc": "为了推动TRPG文化的发展，我们将与企业、学校、社区建立长期合作关系，以期创造对多方有利的局面。",
		"stats-users": "活跃用户",
		"stats-events": "活动举办",
		"stats-cities": "合作城市",
		"stats-satisfaction": "客户满意度",
		"business-title": "主营业务",
		"business-desc": "从线下活动规划，到影视配音服务，我们提供多种以TRPG为主题的服务项目，并可为客户量身订做专属的解决方案",
		"business-1-title": "TRPG活动规划",
		"business-1-sub1": "企业团体活动",
		"business-1-sub1-desc": "善用TRPG强互动性的特点，在玩游戏的同时，可以有效提升同仁间的沟通效率及团队向心力，使公司整体士气提升。",
		"business-1-sub2": "学校营队活动",
		"business-1-sub2-desc": "将教育课程与TRPG游戏方式结合，并通过营队方式呈现，让学生在充满趣味的游戏过程中培养想象力、逻辑思维及社交技巧。",
		"business-2-title": "影视广告配音",
		"business-2-sub1": "影视作品配音",
		"business-2-sub1-desc": "为电影、电视剧、动画等影视作品提供专业配音服务，包括角色配音、旁白配音，并根据作品需求配合调整。",
		"business-2-sub2": "商业广告配音",
		"business-2-sub2-desc": "为企业广告、产品宣传片、企业形象片等提供配音服务，根据不同的风格和需求，选择合适的配音表现方式。",
		"business-3-title": "文创品牌经营",
		"business-3-sub1": "谷子小物制作",
		"business-3-sub1-desc": "协助客户制作其自有品牌的周边产品，并可根据品牌需求，协助设计对应的产品行销策略。",
		"business-3-sub2": "正版商品贩售",
		"business-3-sub2-desc": "与知名IP合作，独家贩售正版授权的谷子套组，并同时提供线下及线上商店贩售通路。",
		"business-4-title": "教育与培训",
		"business-4-sub1": "专业主持培训",
		"business-4-sub1-desc": "以讲座、课程及团务实战的方式，持续培养专业TRPG主持人，让桌上角色扮演的火种得以遍地开花。",
		"business-4-sub2": "剧本创作指导",
		"business-4-sub2-desc": "为TRPG爱好者和从业者提供剧本创作指导，除了提升故事深度，也能因应教育或业界需求，设计独特的游戏内涵。",
		"contact-title": "联络我们",
		"contact-desc": "如果您有任何问题或合作意向，请随时联络我们。",
		"contact-info": "联络资讯",
		"contact-address-title": "地址",
		"contact-address": "新竹市东区",
		"contact-email-title": "电子邮件",
		"contact-email": "lionstrpgvault@gmail.com",
		"contact-hours-title": "营业时间",
		"contact-hours": "10:00-20:00",
		"contact-follow": "关注我们",
		"contact-link": "点击下方按钮获取活动最新资讯，商务合作请洽询FB粉专",
		"footer-company": "胖橘文化有限公司",
		"footer-desc": "本公司以TRPG为核心，提供企业及学校活动规划、影视配音等多元化服务，帮助现代人减轻压力、增进交流。",
		"footer-quicklinks": "快速链接",
		"footer-home": "首页",
		"footer-mission": "经营理念",
		"footer-business": "主营业务",
		"footer-contact": "联系我们",
		"footer-services": "服务项目",
		"footer-service-1": "TRPG活动企划",
		"footer-service-2": "影视广告配音",
		"footer-service-3": "文化体验服务",
		"footer-service-4": "培训与指导",
		"footer-address": "TRPG活动企划",
		"footer-email": "lionstrpgvault@gmail.com",
		"footer-hours": "10:00-20:00"
	},
	"en": {
		"company-name": "Orange Neko Ltd.",
		"nav-home": "Home",
		"nav-mission": "Mission",
		"nav-business": "Business",
		"nav-contact": "Contact Us",
		"hero-title": "Orange Neko<br>TRPG Experience Platform",
		"hero-desc": "Explore fantasy worlds, unleash imagination, and build genuine connections",
		"hero-btn-1": "Experience Now",
		"hero-btn-2": "Learn More",
		"home-company-title": "Company Introduction",
		"home-company-desc": "Founded in 2025, Fat Orange Culture Co., Ltd. aims to relieve stress for modern people with busy lives and reignite vitality in the gaming world.",
		"home-company-desc2": "We specialize in planning various TRPG-themed activities, creating a relaxing, fun, and imaginative space where people can experience different roles and stories while discovering many possibilities in life.",
		"home-stats-1": "Active Users",
		"home-stats-2": "Events Held",
		"home-stats-3": "Satisfaction",
		"home-events-title": "Latest Events",
		"home-events-more": "View All",
		"event-tag-new": "New Event",
		"event-1-title": "TRPG in Hsinchu",
		"event-1-desc": "Regular novice promotion activities held in the Hsinchu area, welcome TRPG enthusiasts to join in the fun.",
		"event-register": "Register Now",
		"event-tag-featured": "Featured",
		"event-2-title": "Special Event",
		"event-2-desc": "Friends who love the world of ⚔️ swords and magic 🔥 are welcome to experience the charm of tabletop role-playing games together!",
		"event-tag-popular": "Popular",
		"event-3-title": "TRPG of classmates",
		"event-3-desc": "A unique TRPG group running event has been created specifically for all students, allowing the wonderful journey in the fantasy world to relieve the pressure of life and bring you the courage to face schoolwork and the future.",
		"home-partners": "Partners",
		"partners1": "LionsTRPGVault",
		"partners2": "Crazy Hospital",
		"partners3": "Board Space",
		"mission-title": "Mission",
		"mission-desc": "We create connections through TRPG to help stressed modern people regain motivation and vision for life.",
		"mission-1-title": "Caring for Modern People",
		"mission-1-desc": "Highly immersive TRPG games help alleviate the pressure from study, work, and life, and rediscover the rhythm of life.",
		"mission-2-title": "Activating Communities",
		"mission-2-desc": "We are committed to enabling game-loving friends to strengthen communication between people by participating in gatherings and activities through TRPG.",
		"mission-3-title": "Innovative Development",
		"mission-3-desc": "By combining culture, education, and commerce, we provide customers with new forms of tabletop role-playing activities and unique experiences.",
		"mission-4-title": "Win-Win Cooperation",
		"mission-4-desc": "To promote the development of TRPG culture, we will establish long-term partnerships with enterprises, schools, and communities to create a beneficial situation for multiple parties.",
		"stats-users": "Active Users",
		"stats-events": "Events Held",
		"stats-cities": "Cooperative Cities",
		"stats-satisfaction": "Customer Satisfaction",
		"business-title": "Main Business",
		"business-desc": "From offline event planning to film and television dubbing services, we provide a variety of TRPG-themed services and can tailor exclusive solutions for customers.",
		"business-1-title": "TRPG Event Planning",
		"business-1-sub1": "Corporate Group Activities",
		"business-1-sub1-desc": "Utilizing the highly interactive nature of TRPG, while playing games, it can effectively improve communication efficiency and team cohesion among colleagues, enhancing overall company morale.",
		"business-1-sub2": "School Camp Activities",
		"business-1-sub2-desc": "Combining educational courses with TRPG gaming methods and presenting them through camps, allowing students to cultivate imagination, logical thinking, and social skills in a fun gaming process.",
		"business-2-title": "Film and Television Advertising Dubbing",
		"business-2-sub1": "Film and Television Dubbing",
		"business-2-sub1-desc": "Providing professional dubbing services for films, TV dramas, animations, etc., including character dubbing and narration dubbing, and adjusting according to the needs of the work.",
		"business-2-sub2": "Commercial Advertising Dubbing",
		"business-2-sub2-desc": "Providing dubbing services for corporate advertisements, product promotion videos, corporate image videos, etc., and selecting appropriate dubbing expressions according to different styles and needs.",
		"business-3-title": "Cultural and Creative Brand Management",
		"business-3-sub1": "Merchandise Production",
		"business-3-sub1-desc": "Assisting customers in producing peripheral products for their own brands, and can assist in designing corresponding product marketing strategies according to brand needs.",
		"business-3-sub2": "Authentic Product Sales",
		"business-3-sub2-desc": "Cooperating with well-known IPs to exclusively sell officially licensed merchandise sets, and providing both offline and online store sales channels.",
		"business-4-title": "Education and Training",
		"business-4-sub1": "Professional Host Training",
		"business-4-sub1-desc": "Continuously cultivating professional TRPG hosts through lectures, courses, and practical team training, allowing the spark of tabletop role-playing to spread widely.",
		"business-4-sub2": "Script Creation Guidance",
		"business-4-sub2-desc": "Providing script creation guidance for TRPG enthusiasts and practitioners, which not only enhances story depth but also designs unique game connotations to meet educational or industry needs.",
		"contact-title": "Contact Us",
		"contact-desc": "If you have any questions or cooperation intentions, please contact us at any time.",
		"contact-info": "Contact Information",
		"contact-address-title": "Address",
		"contact-address": "East District, Hsinchu City",
		"contact-email-title": "Email",
		"contact-email": "lionstrpgvault@gmail.com",
		"contact-hours-title": "Business Hours",
		"contact-hours": "10:00-20:00",
		"contact-follow": "Follow Us",
		"contact-link": "Click the button below to get the latest event information. For business cooperation, please contact our Facebook fan page.",
		"footer-company": "Fat Orange Culture Co., Ltd.",
		"footer-desc": "Our company takes TRPG as the core, providing diversified services such as corporate and school event planning and film and television dubbing, helping modern people reduce stress and enhance communication.",
		"footer-quicklinks": "Quick Links",
		"footer-home": "Home",
		"footer-mission": "Mission",
		"footer-business": "Main Business",
		"footer-contact": "Contact Us",
		"footer-services": "Service Items",
		"footer-service-1": "TRPG Event Planning",
		"footer-service-2": "Film and Television Advertising Dubbing",
		"footer-service-3": "Cultural Experience Services",
		"footer-service-4": "Training and Guidance",
		"footer-address": "TRPG Event Planning",
		"footer-email": "lionstrpgvault@gmail.com",
		"footer-hours": "10:00-20:00"
	},
	"ja": {
		"company-name": "胖橘文化有限公司",
		"nav-home": "ホーム",
		"nav-mission": "経営理念",
		"nav-business": "主な事業",
		"nav-contact": "お問い合わせ",
		"hero-title": "胖橘文化<br>TRPG体験プラットフォーム",
		"hero-desc": "幻想的な世界を探検し、想像力を解き放ち、真摯なつながりを築きます",
		"hero-btn-1": "今すぐ体験",
		"hero-btn-2": "もっと詳しく",
		"home-company-title": "会社概要",
		"home-company-desc": "胖橘文化有限公司は2025年に設立され、生活が多忙な現代人のストレス軽減とゲーム世界での生命力の再燃を目的としています。",
		"home-company-desc2": "当社はさまざまなTRPGテーマのイベント企画を得意とし、リラックスできて楽しく、想像力に富んだ空間を創造し、人々がさまざまな役割と物語を体験すると同時に、人生の多くの可能性に気づくことができます。",
		"home-stats-1": "活躍ユーザー",
		"home-stats-2": "開催イベント",
		"home-stats-3": "満足度",
		"home-events-title": "最新イベント",
		"home-events-more": "すべて表示",
		"event-tag-new": "新イベント",
		"event-1-title": "新竹でのTRPG",
		"event-1-desc": "新竹地区で定期的に開催される初心者向けのプロモーションイベントで、TRPG愛好者の方もぜひご参加ください。",
		"event-register": "すぐに登録",
		"event-tag-featured": "精選",
		"event-2-title": "フェアイベント",
		"event-2-desc": "⚔️剣と魔法🔥の世界を好きな方、是非一緒に卓上ロールプレイングゲームの魅力を体験しましょう！",
		"event-tag-popular": "人気",
		"event-3-title": "クラスメイトのTRPG",
		"event-3-desc": "すべての学生向けに特別に作成されたユニークな TRPG グループ ランニング イベントでは、ファンタジーの世界への素晴らしい旅を通じて生活のプレッシャーを和らげ、学業や将来に立ち向かう勇気を得ることができます。",
		"home-partners": "パートナー",
		"partners1": "老獅の宝庫",
		"partners2": "病院は狂っている",
		"partners3": "謎宝空間",
		"mission-title": "経営理念",
		"mission-desc": "当社はTRPGを通じてつながりを創造し、ストレスに満ちた現代人が生活に対する動力と憧憬を再び手に入れるのを支援します。",
		"mission-1-title": "現代人への配慮",
		"mission-1-desc": "没入感の強いTRPGゲームは、現在の人々の学習、仕事、生活からのストレスを和らげ、生活のリズムを再見つけるのに役立ちます。",
		"mission-2-title": "コミュニティ活性化",
		"mission-2-desc": "当社はゲームを愛する友人がTRPGを通じて集まりやイベントに参加し、人と人の交流を強化できるように努めています。",
		"mission-3-title": "イノベーティブな発展",
		"mission-3-desc": "文化、教育、商業の三者を結合することで、当社は顧客に新しい卓上ロールプレイングイベントの形式とユニークな体験を提供します。",
		"mission-4-title": "協力して双方向に利益を生む",
		"mission-4-desc": "TRPG文化の発展を推進するため、当社は企業、学校、コミュニティと長期的なパートナーシップを築き、多方面に利益をもたらす局面を創造することを目指します。",
		"stats-users": "活躍ユーザー",
		"stats-events": "開催イベント",
		"stats-cities": "協力都市",
		"stats-satisfaction": "顧客満足度",
		"business-title": "主な事業",
		"business-desc": "オフラインイベント企画から映画・テレビの吹き替えサービスまで、当社はTRPGをテーマとするさまざまなサービスを提供し、顧客に合わせた専用のソリューションを提供することができます。",
		"business-1-title": "TRPGイベント企画",
		"business-1-sub1": "企業グループイベント",
		"business-1-sub1-desc": "TRPGの高い相互作用性を生かし、ゲームを楽しむ同時に、同僚間のコミュニケーション効率とチームの団結力を効果的に向上させ、会社全体の士気を高めます。",
		"business-1-sub2": "学校キャンプイベント",
		"business-1-sub2-desc": "教育課程をTRPGゲーム方式と結合し、キャンプ方式で提示することで、学生が楽しいゲーム体験の中で想像力、論理的思考力、社交スキルを育成できます。",
		"business-2-title": "映画・テレビ広告の吹き替え",
		"business-2-sub1": "映画・テレビ作品の吹き替え",
		"business-2-sub1-desc": "映画、テレビドラマ、アニメなどの映像作品に専門的な吹き替えサービスを提供し、キャラクター吹き替え、ナレーション吹き替えを含め、作品のニーズに合わせて調整します。",
		"business-2-sub2": "商業広告の吹き替え",
		"business-2-sub2-desc": "企業広告、製品プロモーションビデオ、企業イメージビデオなどに吹き替えサービスを提供し、異なるスタイルとニーズに合わせて適切な吹き替え表現方法を選択します。",
		"business-3-title": "クルチャークリエイティブブランド経営",
		"business-3-sub1": "グッズ製作",
		"business-3-sub1-desc": "顧客が独自ブランドの周辺商品を製作するのを支援し、ブランドのニーズに応じて、対応する製品マーケティング戦略の設計を支援することができます。",
		"business-3-sub2": "正規品販売",
		"business-3-sub2-desc": "有名IPと協力し、正規ライセンスのグッズセットを独占的に販売し、オフラインとオンラインストアの両方で販売チャネルを提供します。",
		"business-4-title": "教育とトレーニング",
		"business-4-sub1": "プロフェッショナルホストトレーニング",
		"business-4-sub1-desc": "講座、コース、チーム実践の方法で、専門的なTRPGホストを継続的に育成し、卓上ロールプレイングの火種が各地で広がるようにします。",
		"business-4-sub2": "脚本作成指導",
		"business-4-sub2-desc": "TRPG愛好者と従業員に脚本作成指導を提供し、物語の深さを高めるだけでなく、教育や業界のニーズに応じて、ユニークなゲームの内容を設計することができます。",
		"contact-title": "お問い合わせ",
		"contact-desc": "ご質問やご連絡があれば、いつでもお問い合わせください。",
		"contact-info": "連絡先情報",
		"contact-address-title": "住所",
		"contact-address": "新竹市東区",
		"contact-email-title": "メールアドレス",
		"contact-email": "lionstrpgvault@gmail.com",
		"contact-hours-title": "営業時間",
		"contact-hours": "10:00-20:00",
		"contact-follow": "フォロー",
		"contact-link": "以下のボタンをクリックして最新のイベント情報を入手し、ビジネス提携についてはFBファンページまでお問い合わせください",
		"footer-company": "胖橘文化有限公司",
		"footer-desc": "当社はTRPGを核として、企業や学校のイベント企画、映画・テレビの吹き替えなど多様なサービスを提供し、現代人のストレス軽減と交流促進を支援します。",
		"footer-quicklinks": "クイックリンク",
		"footer-home": "ホーム",
		"footer-mission": "経営理念",
		"footer-business": "主な事業",
		"footer-contact": "お問い合わせ",
		"footer-services": "サービス項目",
		"footer-service-1": "TRPGイベント企画",
		"footer-service-2": "映画・テレビ広告の吹き替え",
		"footer-service-3": "文化体験サービス",
		"footer-service-4": "トレーニングと指導",
		"footer-address": "TRPGイベント企画",
		"footer-email": "lionstrpgvault@gmail.com",
		"footer-hours": "10:00-20:00"
	},
	"ko": {
		"company-name": "팡주 문화 유한회사",
		"nav-home": "홈",
		"nav-mission": "경영이념",
		"nav-business": "주요 사업",
		"nav-contact": "연락하기",
		"hero-title": "팡주 문화<br>TRPG 체험 플랫폼",
		"hero-desc": "기상천외한 세계를 탐험하고 상상력을 해방하며 진지한 연결을 구축합니다",
		"hero-btn-1": "즉시 체험",
		"hero-btn-2": "자세히 알아보기",
		"home-company-title": "회사 소개",
		"home-company-desc": "팡주 문화 유한회사는 2025년에 설립되어 삶이 바쁜 현대인들에게 스트레스를 완화하고 게임 세계에서 생명력을 다시 불피우는 것을 목표로 합니다.",
		"home-company-desc2": "우리는 다양한 TRPG 테마 행사를 기획하는 데 뛰어나며, 휴식을 취하고 재미있고 상상력이 넘치는 공간을 만들어 사람들이 다양한 역할과 이야기를 체험하면서 삶의 많은 가능성을 발견할 수 있도록 돕습니다.",
		"home-stats-1": "활동 사용자",
		"home-stats-2": "개최된 행사",
		"home-stats-3": "만족도",
		"home-events-title": "최신 행사",
		"home-events-more": "전체 보기",
		"event-tag-new": "신규 행사",
		"event-1-title": "신주에서의 TRPG",
		"event-1-desc": "신주 지역에서 정기적으로 열리는 신규 사용자 홍보 행사로, TRPG 애호가 여러분도 함께 즐기실 수 있습니다.",
		"event-register": "즉시 신청",
		"event-tag-featured": "精选",
		"event-2-title": "전용 행사",
		"event-2-desc": "⚔️검과 마법🔥세상을 좋아하는 친구들, 함께 테이블 롤플레이 게임의 매력을 체험해 보세요!",
		"event-tag-popular": "인기",
		"event-3-title": "반 친구들의 TRPG",
		"event-3-desc": "모든 학생들을 위해 특별히 만들어진 독특한 TRPG 그룹 달리기 이벤트를 통해 판타지 세계에서의 멋진 여행을 통해 삶의 압박감을 해소하고 학교 과제와 미래에 맞설 용기를 얻을 수 있습니다.",
		"home-partners": "협력 파트너",
		"partners1": "로시의 보물창고",
		"partners2": "병원이 미쳤어",
		"partners3": "수수께끼 보물 공간",
		"mission-title": "경영이념",
		"mission-desc": "우리는 TRPG를 통해 연결고리를 만들어 스트레스에 찬 현대인들이 삶에 대한 동력과 환상을 다시 얻을 수 있도록 돕겠습니다.",
		"mission-1-title": "현대인에 대한 관怀",
		"mission-1-desc": "몰입감이 강한 TRPG 게임은 현재 사람들이 학습, 일, 삶에서 받는 스트레스를 완화하고 삶의 리듬을 다시 찾는 데 도움이 됩니다.",
		"mission-2-title": "社群 활성화",
		"mission-2-desc": "우리는 게임을 좋아하는 친구들이 TRPG를 통해 모임과 행사에 참여하여 사람들 사이의交流를 더욱 강화할 수 있도록 노력합니다.",
		"mission-3-title": "혁신 발전",
		"mission-3-desc": "문화, 교육, 상업을 결합하여 고객에게全新한 테이블 롤플레이 행사 형식과 독특한 체험을 제공할 것입니다.",
		"mission-4-title": "협력 공융",
		"mission-4-desc": "TRPG 문화의 발전을 위해 우리 회사는 기업, 학교, 지역사회와 장기 협력 관계를 맺어 다방에 이익을 가져다주는局面을 창조할 것입니다.",
		"stats-users": "활동 사용자",
		"stats-events": "개최된 행사",
		"stats-cities": "협력 도시",
		"stats-satisfaction": "고객 만족도",
		"business-title": "주요 사업",
		"business-desc": "오프라인 행사 계획부터 영화·TV 딥핑 서비스까지 TRPG를 테마로 한 다양한 서비스를 제공하며 고객에게 맞춤형 전용 솔루션을 제안할 수 있습니다.",
		"business-1-title": "TRPG 행사 계획",
		"business-1-sub1": "기업 단체 행사",
		"business-1-sub1-desc": "TRPG의 강력한 상호작용성을 활용하여 게임을 즐기면서 동료 간의 소통 효율과 팀 응집력을 효과적으로 높여 회사 전체的士氣를 끌어올립니다.",
		"business-1-sub2": "학교 캠프 행사",
		"business-1-sub2-desc": "교육 과정을 TRPG 게임 방식과 결합하여 캠프 방식으로 선보여 학생들이 재미있는 게임 과정에서 상상력, 논리 사고력 및 사교 기술을 기르도록 돕습니다.",
		"business-2-title": "영상 광고 딥핑",
		"business-2-sub1": "영상 작품 딥핑",
		"business-2-sub1-desc": "영화, TV 드라마, 애니메이션 등의 영상 작품에 전문적인 딥핑 서비스를 제공하며 캐릭터 딥핑, 나레이터 딥핑을 포함하여 작품 요구에 따라 조정합니다.",
		"business-2-sub2": "상업 광고 딥핑",
		"business-2-sub2-desc": "기업 광고, 제품 홍보 영상, 기업 이미지 영상 등에 딥핑 서비스를 제공하며不同的 스타일과需求에 따라 적합한 딥핑 표현 방식을 선택합니다.",
		"business-3-title": "문화 창작 브랜드 경영",
		"business-3-sub1": "굴즈 소품 제작",
		"business-3-sub1-desc": "고객이 자체 브랜드의周边製品을 제작하는 데 도움을 주며 브랜드需求에 따라 해당 제품 마케팅 전략을 디자인할 수 있습니다.",
		"business-3-sub2": "정식 상품 판매",
		"business-3-sub2-desc": "유명 IP와 협력하여 정식 라이선스가 부여된 굴즈 세트를 독점적으로 판매하며 오프라인 및 온라인商店 판매 경로를 동시에 제공합니다.",
		"business-4-title": "교육 및 훈련",
		"business-4-sub1": "전문 진행자 훈련",
		"business-4-sub1-desc": "강연, 코스 및 단체 실전 방식으로 전문적인 TRPG 진행자를 지속적으로 양성하여 테이블 롤플레이의 불꽃이 각지에서 피어나도록 합니다.",
		"business-4-sub2": "대본 창작 지도",
		"business-4-sub2-desc": "TRPG 애호가와 종사자에게 대본 창작 지도를 제공하며 이야기의_DEPTH를 높일 뿐만 아니라 교육이나 산업需求에 따라 독특한 게임 내용을 설계할 수 있습니다.",
		"contact-title": "연락하기",
		"contact-desc": "任何 문제나 협력 의향이 있으시면 언제든지 연락해 주세요.",
		"contact-info": "연락처 정보",
		"contact-address-title": "주소",
		"contact-address": "신주시 동구",
		"contact-email-title": "이메일",
		"contact-email": "lionstrpgvault@gmail.com",
		"contact-hours-title": "영업 시간",
		"contact-hours": "10:00-20:00",
		"contact-follow": "우리에게 팔로우",
		"contact-link": "아래 버튼을 클릭하여 행사 최신 정보를 얻으시고, 비즈니스 협력은 FB 팬 페이지에 문의하세요",
		"footer-company": "팡주 문화 유한회사",
		"footer-desc": "회사는 TRPG를 핵심으로 기업 및 학교 행사 계획, 영상 딥핑 등 다양한 서비스를 제공하여 현대인들이 스트레스를 줄이고交流를 높일 수 있도록 돕습니다.",
		"footer-quicklinks": "빠른 링크",
		"footer-home": "홈",
		"footer-mission": "경영이념",
		"footer-business": "주요 사업",
		"footer-contact": "연락하기",
		"footer-services": "서비스 항목",
		"footer-service-1": "TRPG 행사 기획",
		"footer-service-2": "영상 광고 딥핑",
		"footer-service-3": "문화 체험 서비스",
		"footer-service-4": "훈련 및 지도",
		"footer-address": "TRPG 행사 기획",
		"footer-email": "lionstrpgvault@gmail.com",
		"footer-hours": "10:00-20:00"
	},
	"fr": {
		"company-name": "Fat Orange Culture Co., Ltd.",
		"nav-home": "Accueil",
		"nav-mission": "Idéologie d'exploitation",
		"nav-business": "Activités principales",
		"nav-contact": "Contactez-nous",
		"hero-title": "Fat Orange Culture<br>Plateforme d'expérience TRPG",
		"hero-desc": "Explorez des mondes fantastiques, libérez votre imagination et établissez des liens authentiques",
		"hero-btn-1": "Expérimenter immédiatement",
		"hero-btn-2": "En savoir plus",
		"home-company-title": "Présentation de l'entreprise",
		"home-company-desc": "Fat Orange Culture Co., Ltd. a été fondée en 2025 avec le but de soulager le stress des personnes modernes aux vies肠溶片 et de redonner de la vitalité dans le monde des jeux.",
		"home-company-desc2": "Nous sommes spécialisés dans la planification d'activités thématiques TRPG, créant un espace relaxant, amusant et plein d'imagination, permettant aux gens d'expérimenter différents personnages et histoires tout en découvrant de nombreuses possibilités de la vie.",
		"home-stats-1": "Utilisateurs actifs",
		"home-stats-2": "Activités organisées",
		"home-stats-3": "Satisfaction",
		"home-events-title": "Dernières activités",
		"home-events-more": "Voir tout",
		"event-tag-new": "Nouvelle activité",
		"event-1-title": "TRPG à Hsinchu",
		"event-1-desc": "Activité de promotion novices organisée régulièrement dans la région de Hsinchu, ouverte aux amateurs de TRPG.",
		"event-register": "S'inscrire immédiatement",
		"event-tag-featured": "Sélectionné",
		"event-2-title": "Activité spéciale",
		"event-2-desc": "Aux amis qui aiment le monde de ⚔️épées et de magie 🔥, venez découvrir le charme des jeux de rôle de table !",
		"event-tag-popular": "Populaire",
		"event-3-title": "TRPG des camarades de classe",
		"event-3-desc": "Un événement de course de groupe TRPG unique a été créé spécifiquement pour tous les étudiants, permettant au merveilleux voyage dans le monde fantastique de soulager la pression de la vie et de vous apporter le courage d'affronter les devoirs et l'avenir.",
		"home-partners": "Partenaires",
		"partners1": "Trésor de Lao Shi",
		"partners2": "L'hôpital est fou",
		"partners3": "Espace Mystère Trésor",
		"mission-title": "Idéologie d'exploitation",
		"mission-desc": "Nous créerons des liens grâce au TRPG pour aider les personnes modernes stressées à retrouver leur motivation et leur espoir pour la vie.",
		"mission-1-title": "Soutien aux personnes modernes",
		"mission-1-desc": "Les jeux TRPG à forte immersion aident à soulager le stress des personnes actuelles provenant de l'apprentissage, du travail et de la vie, et à retrouver le rythme de la vie.",
		"mission-2-title": "Dynamisation de la communauté",
		"mission-2-desc": "Nous nous efforçons de permettre aux amis amateurs de jeux de participer à des réunions et des activités via le TRPG, renforçant ainsi les échanges entre les personnes.",
		"mission-3-title": "Développement innovant",
		"mission-3-desc": "En combinant la culture, l'éducation et le commerce, nous offrons à nos clients de nouvelles formes d'activités de jeux de rôle de table et des expériences uniques.",
		"mission-4-title": "Coopération gagnant-gagnant",
		"mission-4-desc": "Afin de promouvoir le développement de la culture TRPG, nous établirons des partenariats à long terme avec des entreprises, des écoles et des communautés pour créer une situation avantageuse pour plusieurs parties.",
		"stats-users": "Utilisateurs actifs",
		"stats-events": "Activités organisées",
		"stats-cities": "Villes coopérantes",
		"stats-satisfaction": "Satisfaction des clients",
		"business-title": "Activités principales",
		"business-desc": "De la planification d'activités offline à la doublage pour le cinéma et la télévision, nous offrons une variété de services thématiques TRPG et pouvons concevoir des solutions exclusives pour les clients.",
		"business-1-title": "Planification d'activités TRPG",
		"business-1-sub1": "Activités de groupes d'entreprises",
		"business-1-sub1-desc": "En utilisant les caractéristiques fortement interactives du TRPG, tout en jouant, cela améliore efficacement l'efficacité de la communication et la cohésion d'équipe entre collègues, augmentant le moral d'ensemble de l'entreprise.",
		"business-1-sub2": "Activités de camp scolaire",
		"business-1-sub2-desc": "Combiner les cours éducatifs avec la manière de jouer au TRPG et les présenter sous forme de camp, permettant aux étudiants de développer leur imagination, leur pensée logique et leurs compétences sociales dans un processus de jeu amusant.",
		"business-2-title": "Doublage publicitaire pour le cinéma et la télévision",
		"business-2-sub1": "Doublage de œuvres cinématographiques et télévisées",
		"business-2-sub1-desc": "Fournir des services de doublage professionnels pour les films, séries télévisées, animations, etc., y compris le doublage de personnages et le doublage de commentaires, et ajuster en fonction des besoins de l'œuvre.",
		"business-2-sub2": "Doublage publicitaire commercial",
		"business-2-sub2-desc": "Fournir des services de doublage pour publicités d'entreprises, vidéos de promotion de produits, vidéos d'image d'entreprise, etc., et choisir des modes d'expression de doublage appropriés en fonction des styles et des besoins différents.",
		"business-3-title": "Gestion de marque culturelle et créative",
		"business-3-sub1": "Production de petits articles",
		"business-3-sub1-desc": "Assister les clients dans la production de produits accessoires de leur propre marque, et pouvoir aider à concevoir des stratégies de marketing de produits correspondantes en fonction des besoins de la marque.",
		"business-3-sub2": "Vente de produits officiels",
		"business-3-sub2-desc": "Coopérer avec des IP célèbres pour vendre exclusivement des ensembles de produits officiellement autorisés, et fournir simultanément des canaux de vente en ligne et en magasin physique.",
		"business-4-title": "Éducation et formation",
		"business-4-sub1": "Formation professionnelle de présentateurs",
		"business-4-sub1-desc": "Former en continu des présentateurs professionnels TRPG par le biais de conférences, de cours et de pratiques en équipe, permettant ainsi que la flamme des jeux de rôle de table s'étende partout.",
		"business-4-sub2": "Conseil en création de scénarios",
		"business-4-sub2-desc": "Offrir des conseils en création de scénarios aux amateurs et aux professionnels du TRPG, afin non seulement d'améliorer la profondeur des histoires, mais également de concevoir des contenus de jeu uniques en fonction des besoins éducatifs ou professionnels.",
		"contact-title": "Contactez-nous",
		"contact-desc": "Si vous avez des questions ou des intentions de coopération, n'hésitez pas à nous contacter.",
		"contact-info": "Informations de contact",
		"contact-address-title": "Adresse",
		"contact-address": "District Est, Ville de Hsinchu",
		"contact-email-title": "Email",
		"contact-email": "lionstrpgvault@gmail.com",
		"contact-hours-title": "Heures d'ouverture",
		"contact-hours": "10:00-20:00",
		"contact-follow": "Suivez-nous",
		"contact-link": "Cliquez sur le bouton ci-dessous pour obtenir les dernières informations sur les activités. Pour les coopérations commerciales, contactez notre page fan FB.",
		"footer-company": "Fat Orange Culture Co., Ltd.",
		"footer-desc": "Notre entreprise, centrée sur le TRPG, propose des services diversifiés tels que la planification d'activités pour entreprises et écoles, le doublage cinématographique et télévisuel, afin d'aider les personnes modernes à réduire le stress et à renforcer les échanges.",
		"footer-quicklinks": "Liens rapides",
		"footer-home": "Accueil",
		"footer-mission": "Idéologie d'exploitation",
		"footer-business": "Activités principales",
		"footer-contact": "Contactez-nous",
		"footer-services": "Services proposés",
		"footer-service-1": "Planification d'activités TRPG",
		"footer-service-2": "Doublage publicitaire cinématographique et télévisuel",
		"footer-service-3": "Services d'expérience culturelle",
		"footer-service-4": "Formation et conseil",
		"footer-address": "Planification d'activités TRPG",
		"footer-email": "lionstrpgvault@gmail.com",
		"footer-hours": "10:00-20:00"
	},
	"de": {
		"company-name": "Fat Orange Culture Co., Ltd.",
		"nav-home": "Startseite",
		"nav-mission": "Betriebsphilosophie",
		"nav-business": "Hauptgeschäft",
		"nav-contact": "Kontaktieren Sie uns",
		"hero-title": "Fat Orange Culture<br>TRPG-Erlebnisplattform",
		"hero-desc": "Entdecken Sie märchenhafte Welten, lösen Sie Ihre Fantasie frei und schaffen Sie ehrliche Verbindungen",
		"hero-btn-1": "Sofort erleben",
		"hero-btn-2": "Weiterlesen",
		"home-company-title": "Unternehmensvorstellung",
		"home-company-desc": "Fat Orange Culture Co., Ltd. wurde 2025 gegründet und zielt darauf ab, den Stress moderner Menschen mit hektischem Lebensrhythmus zu lindern und in der Spielwelt wieder Lebensfreude zu wecken.",
		"home-company-desc2": "Wir sind Experten in der Planung verschiedener TRPG-Themenaktivitäten, schaffen einen entspannten, unterhaltsamen und fantasievollen Raum, in dem Menschen verschiedene Rollen und Geschichten erleben und gleichzeitig viele Möglichkeiten des Lebens entdecken können.",
		"home-stats-1": "Aktive Benutzer",
		"home-stats-2": "Organisierte Veranstaltungen",
		"home-stats-3": "Zufriedenheit",
		"home-events-title": "Neuste Veranstaltungen",
		"home-events-more": "Alle anzeigen",
		"event-tag-new": "Neue Veranstaltung",
		"event-1-title": "TRPG in Hsinchu",
		"event-1-desc": "Regelmäßig in der Region Hsinchu stattfindende Einsteiger-Präsentationsveranstaltung, zu der auch TRPG-Enthusiasten eingeladen sind.",
		"event-register": "Sofort anmelden",
		"event-tag-featured": "Ausgewählt",
		"event-2-title": "Sondervorstellung",
		"event-2-desc": "Freunde, die die Welt von ⚔️ Schwertern und Magie 🔥 lieben, sind willkommen, den Charme von Tischrollenspielen kennenzulernen!",
		"event-tag-popular": "Beliebt",
		"event-3-title": "TRPG von Klassenkameraden",
		"event-3-desc": "Speziell für alle Schüler wurde ein einzigartiges TRPG-Gruppenlaufevent geschaffen, das eine wunderbare Reise in die Fantasiewelt ermöglicht, den Druck des Lebens abzubauen und Ihnen den Mut zu geben, sich den Schularbeiten und der Zukunft zu stellen.",
		"home-partners": "Partner",
		"partners1": "Lao Shis Schatzkammer",
		"partners2": "Das Krankenhaus ist verrückt",
		"partners3": "Rätsel-Schatz-Raum",
		"mission-title": "Betriebsphilosophie",
		"mission-desc": "Wir werden Verbindungen durch TRPG schaffen, um stressbelastete Menschen der Gegenwart zu helfen, die Motivation und die Sehnsucht für das Leben wiederzufinden.",
		"mission-1-title": "Sorge für moderne Menschen",
		"mission-1-desc": "TRPG-Spiele mit starker Immersion helfen, den Stress von Lernen, Arbeiten und Leben der heutigen Menschen zu lindern und den Lebensrhythmus wiederzufinden.",
		"mission-2-title": "Aktivierung der Gemeinschaft",
		"mission-2-desc": "Wir setzen uns dafür ein, dass Freunde, die gerne spielen, durch TRPG an Treffen und Veranstaltungen teilnehmen können, um den Austausch zwischen Menschen zu stärken.",
		"mission-3-title": "Innovatives Wachstum",
		"mission-3-desc": "Indem wir Kultur, Bildung und Handel kombinieren, bieten wir unseren Kunden neue Formen von Tischrollenspielaktivitäten und einzigartige Erfahrungen.",
		"mission-4-title": "Win-Win-Kooperation",
		"mission-4-desc": "Um die Entwicklung der TRPG-Kultur zu fördern, werden wir langfristige Kooperationsbeziehungen mit Unternehmen, Schulen und Gemeinden aufbauen, um eine Situation zu schaffen, die für mehrere Parteien vorteilhaft ist.",
		"stats-users": "Aktive Benutzer",
		"stats-events": "Organisierte Veranstaltungen",
		"stats-cities": "Kooperationsstädte",
		"stats-satisfaction": "Kundenzufriedenheit",
		"business-title": "Hauptgeschäft",
		"business-desc": "Von der Planung offline-Aktivitäten bis zur Synchronisationsdienstleistung für Film und Fernsehen bieten wir eine Vielzahl von TRPG-Themen-Diensten an und können maßgeschneiderte Lösungen für Kunden anbieten.",
		"business-1-title": "TRPG-Aktivitätsplanung",
		"business-1-sub1": "Unternehmensgruppenaktivitäten",
		"business-1-sub1-desc": "Durch die Nutzung der stark interaktiven Eigenschaften von TRPG kann die Kommunikationseffizienz und Teamgeist zwischen Kollegen effektiv verbessert werden, wodurch der allgemeine Teamgeist der Firma gesteigert wird.",
		"business-1-sub2": "Schulcamp-Aktivitäten",
		"business-1-sub2-desc": "Kombinieren von Bildungsmodulen mit TRPG-Spielweisen und Präsentieren durch Camp-Formate, um den Schülern die Entwicklung von Fantasie, logischem Denken und sozialen Fähigkeiten in einem unterhaltsamen Spielprozess zu ermöglichen.",
		"business-2-title": "Synchronisation für Film und Fernsehwerbung",
		"business-2-sub1": "Synchronisation von Film- und Fernsehwerken",
		"business-2-sub1-desc": "Bereitstellung professioneller Synchronisationsdienste für Filme, Fernsehserien, Animationen usw., einschließlich Rollensynchronisation und Voice-over, und Anpassung an die Bedürfnisse des Werks.",
		"business-2-sub2": "Werbesynchronisation für kommerzielle Anzeigen",
		"business-2-sub2-desc": "Bereitstellung von Synchronisationsdiensten für Unternehmenswerbung, Produktpromotionsfilme, Unternehmensimagefilme usw., und Auswahl geeigneter Synchronisationsweisen basierend auf verschiedenen Stilen und Anforderungen.",
		"business-3-title": "Management kulturell-kreativer Marken",
		"business-3-sub1": "Herstellung von Merchandisingartikeln",
		"business-3-sub1-desc": "Unterstützung bei der Herstellung von Markenartikeln für Kunden und Assistenz bei der Gestaltung entsprechender Produktmarketingstrategien gemäß den Markenbedürfnissen.",
		"business-3-sub2": "Verkauf von offiziellen Produkten",
		"business-3-sub2-desc": "Kooperation mit bekannten IPs zur exklusiven Verbringung offiziell lizenzierter Merchandisesets und gleichzeitig Bereitstellung von Vertriebskanälen für Offline- und Online-Shops.",
		"business-4-title": "Bildung und Training",
		"business-4-sub1": "Professionelle Moderatorenausbildung",
		"business-4-sub1-desc": "Stetige Ausbildung professioneller TRPG-Moderatoren durch Workshops, Kurse und Praxiserfahrungen in Teams, um den Funken des Tischrollenspiels überall zu verbreiten.",
		"business-4-sub2": "Leitfaden zur Drehbucherstellung",
		"business-4-sub2-desc": "Bereitstellung von Drehbuchgestaltungsleitfäden für TRPG-Enthusiasten und Professionals, um nicht nur die Tiefe der Geschichte zu verbessern, sondern auch einzigartige Spielinhalte für Bildungs- oder Branchenbedürfnisse zu entwerfen.",
		"contact-title": "Kontaktieren Sie uns",
		"contact-desc": "Wenn Sie Fragen oder Kooperationsabsichten haben, kontaktieren Sie uns bitte jederzeit.",
		"contact-info": "Kontaktinformationen",
		"contact-address-title": "Adresse",
		"contact-address": "Ostbezirk, Stadt Hsinchu",
		"contact-email-title": "E-Mail",
		"contact-email": "lionstrpgvault@gmail.com",
		"contact-hours-title": "Geschäftszeiten",
		"contact-hours": "10:00-20:00",
		"contact-follow": "Folgen Sie uns",
		"contact-link": "Klicken Sie auf die Schaltfläche unten, um die neuesten Veranstaltungsinformationen zu erhalten. Für geschäftliche Kooperationen wenden Sie sich bitte an unsere Facebook-Fanpage.",
		"footer-company": "Fat Orange Culture Co., Ltd.",
		"footer-desc": "Unsere Firma zielt auf TRPG ab und bietet vielfältige Services wie Unternehmens- und Schulveranstaltungsplanung, Film- und Fernsehsynchronisation, um modernen Menschen bei der Stressreduzierung und Kommunikationssteigerung zu helfen.",
		"footer-quicklinks": "Schnelllinks",
		"footer-home": "Startseite",
		"footer-mission": "Betriebsphilosophie",
		"footer-business": "Hauptgeschäft",
		"footer-contact": "Kontaktieren Sie uns",
		"footer-services": "Serviceleistungen",
		"footer-service-1": "TRPG-Veranstaltungsplanung",
		"footer-service-2": "Synchronisation für Film- und Fernsehwerbung",
		"footer-service-3": "Kulturelle Erfahrungsservice",
		"footer-service-4": "Training und Beratung",
		"footer-address": "TRPG-Veranstaltungsplanung",
		"footer-email": "lionstrpgvault@gmail.com",
		"footer-hours": "10:00-20:00"
	},
	"es":{
	  "company-name": "FatCat Cultura S.L.",
	  "nav-home": "Inicio",
	  "nav-mission": "Filosofía",
	  "nav-business": "Negocios",
	  "nav-contact": "Contáctanos",
	  "hero-title": "FatCat Cultura<br>Plataforma de Experiencias TRPG",
	  "hero-desc": "Explora mundos fantásticos, libera tu imaginación y construye conexiones sinceras",
	  "hero-btn-1": "Experimentar ahora",
	  "hero-btn-2": "Más información",
	  "home-company-title": "Sobre Nosotros",
	  "home-company-desc": "FatCat Cultura S.L. se fundó en 2025 con la misión de ayudar a las personas modernas a aliviar el estrés y reencender la energía vital a través del mundo del juego.",
	  "home-company-desc2": "Somos especialistas en organizar eventos temáticos de TRPG, creando un espacio relajante, divertido e imaginativo, donde se pueden descubrir múltiples posibilidades de la vida al asumir diferentes roles e historias.",
	  "home-stats-1": "Usuarios Activos",
	  "home-stats-2": "Eventos Realizados",
	  "home-stats-3": "Satisfacción",
	  "home-events-title": "Últimos Eventos",
	  "home-events-more": "Ver todos",
	  "event-tag-new": "Nuevo",
	  "event-1-title": "TRPG en Hsinchu",
	  "event-1-desc": "Evento de iniciación fijo en la zona de Hsinchu, también damos la bienvenida a aficionados de TRPG.",
	  "event-register": "Regístrate ahora",
	  "event-tag-featured": "Destacado",
	  "event-2-title": "Evento Especial",
	  "event-2-desc": "¡Amantes del ⚔️ mundo de espada y magia 🔥, venid a experimentar el encanto del juego de rol de mesa!",
	  "event-tag-popular": "Popular",
	  "event-3-title": "TRPG de compañeros de clase",
	  "event-3-desc": "Se ha creado un evento grupal TRPG único específicamente para todos los estudiantes, lo que permite un maravilloso viaje en el mundo de fantasía para aliviar la presión de la vida y brindarle el coraje para enfrentar el trabajo escolar y el futuro.",
	  "home-partners": "Socios",
	  "partners1": "El Tesoro del Viejo León",
	  "partners2": "El hospital está loco",
	  "partners3": "Espacio Mysterio",
	  "mission-title": "Filosofía",
	  "mission-desc": "A través del TRPG creamos conexiones, ayudamos a las personas modernas a recuperar la motivación y la esperanza en la vida.",
	  "mission-1-title": "Cuidado del Ser Moderno",
	  "mission-1-desc": "La inmersión profunda en TRPG ayuda a aliviar la presión de los estudios, trabajo y vida, recuperando el ritmo vital.",
	  "mission-2-title": "Dinamizar la Comunidad",
	  "mission-2-desc": "Nos enfocamos en que los aficionados a los juegos, mediante TRPG, participen en reuniones y actividades, fortaleciendo la interacción humana.",
	  "mission-3-title": "Innovación y Desarrollo",
	  "mission-3-desc": "Combinando cultura, educación y negocio, ofrecemos nuevas formas de actividades TRPG y experiencias únicas a los clientes.",
	  "mission-4-title": "Colaboración Ganar‑Ganar",
	  "mission-4-desc": "Para impulsar la cultura TRPG, establecemos colaboraciones a largo plazo con empresas, escuelas y comunidades, creando situaciones beneficiosas para todos.",
	  "stats-users": "Usuarios Activos",
	  "stats-events": "Eventos Realizados",
	  "stats-cities": "Ciudades Colaboradoras",
	  "stats-satisfaction": "Satisfacción del Cliente",
	  "business-title": "Negocios Principales",
	  "business-desc": "Desde planificación de eventos presenciales hasta doblaje audiovisual, ofrecemos diversos servicios TRPG y soluciones hechas a medida.",
	  "business-1-title": "Planificación de Eventos TRPG",
	  "business-1-sub1": "Eventos Corporativos",
	  "business-1-sub1-desc": "Aprovechando la alta interactividad del TRPG, mejoramos la comunicación y la cohesión del equipo, elevando la moral.",
	  "business-1-sub2": "Campamentos Escolares",
	  "business-1-sub2-desc": "Combinamos currículum educativo con TRPG en formato de campamento, para que estudiantes desarrollen imaginación, lógica y habilidades sociales.",
	  "business-2-title": "Doblaje para Medios y Publicidad",
	  "business-2-sub1": "Doblaje para Medios",
	  "business-2-sub1-desc": "Proveemos doblaje profesional para películas, series, animación, incluyendo personajes y narración, adaptándonos a las necesidades.",
	  "business-2-sub2": "Doblaje Publicitario",
	  "business-2-sub2-desc": "Ofrecemos doblaje para anuncios empresariales, vídeos corporativos e institucionales, escogiendo el estilo apropiado.",
	  "business-3-title": "Gestión de Marca Cultural",
	  "business-3-sub1": "Producción de Merchandising",
	  "business-3-sub1-desc": "Ayudamos a clientes a crear productos de marca, además de diseñar estrategias de marketing de producto.",
	  "business-3-sub2": "Venta de Productos Oficiales",
	  "business-3-sub2-desc": "En cooperación con IPs conocidas, vendemos kits oficiales, tanto en tienda física como online.",
	  "business-4-title": "Educación y Capacitación",
	  "business-4-sub1": "Formación de Moderadores Profesionales",
	  "business-4-sub1-desc": "Con charlas, cursos y práctica grupal, formamos moderadores profesionales de TRPG para expandir esta semilla de juego.",
	  "business-4-sub2": "Asesoría en Creación de Guiones",
	  "business-4-sub2-desc": "Brindamos asesoría en creación de guiones para entusiastas y profesionales de TRPG, elevando la profundidad narrativa y adaptando a necesidades educativas o profesionales.",
	  "contact-title": "Contáctanos",
	  "contact-desc": "Si tienes alguna pregunta o interés en colaboraciones, no dudes en contactarnos.",
	  "contact-info": "Información de Contacto",
	  "contact-address-title": "Dirección",
	  "contact-address": "Distrito Este, Hsinchu",
	  "contact-email-title": "Correo electrónico",
	  "contact-email": "lionstrpgvault@gmail.com",
	  "contact-hours-title": "Horario",
	  "contact-hours": "10:00‑20:00",
	  "contact-follow": "Síguenos",
	  "contact-link": "Haz clic en el botón de abajo para obtener las últimas novedades de eventos; para colaboraciones comerciales, contáctanos en Facebook.",
	  "footer-company": "FatCat Cultura S.L.",
	  "footer-desc": "Nuestra empresa, centrada en TRPG, ofrece planificación de eventos empresariales y escolares, doblaje audiovisual y servicios diversos, ayudando a reducir el estrés y fomentar conexiones.",
	  "footer-quicklinks": "Enlaces Rápidos",
	  "footer-home": "Inicio",
	  "footer-mission": "Filosofía",
	  "footer-business": "Negocios",
	  "footer-contact": "Contáctanos",
	  "footer-services": "Servicios",
	  "footer-service-1": "Planificación TRPG",
	  "footer-service-2": "Doblaje y Publicidad",
	  "footer-service-3": "Servicios Culturales",
	  "footer-service-4": "Formación y Asesoría",
	  "footer-address": "Planificación TRPG",
	  "footer-email": "lionstrpgvault@gmail.com",
	  "footer-hours": "10:00‑20:00"
	},
	"ar": {
	  "company-name": "شركة فاطكات للثقافة المحدودة",
	  "nav-home": "الرئيسية",
	  "nav-mission": "فلسفتنا",
	  "nav-business": "أعمالنا",
	  "nav-contact": "اتصل بنا",
	  "hero-title": "منصة فاطكات<br>لتجارب TRPG",
	  "hero-desc": "اكتشف عوالم خيالية، حرر خيالك، وابنِ صداقات حقيقية",
	  "hero-btn-1": "جرب الآن",
	  "hero-btn-2": "اعرف المزيد",
	  "home-company-title": "نبذة عن الشركة",
	  "home-company-desc": "تأسست شركة فاطكات للثقافة المحدودة في عام 2025 بهدف مساعدة الأشخاص المعاصرين على تخفيف الضغوط وتجديد حيويتهم من خلال عالم الألعاب.",
	  "home-company-desc2": "نحن متخصصون في تنظيم فعاليات TRPG موضوعية، ونسعى لإنشاء مساحة مريحة وممتعة ومليئة بالخيال، حيث يمكن للناس تجربة أدوار وقصص مختلفة واكتشاف إمكانيات الحياة.",
	  "home-stats-1": "المستخدمون النشطون",
	  "home-stats-2": "عدد الفعاليات",
	  "home-stats-3": "مستوى الرضا",
	  "home-events-title": "أحدث الفعاليات",
	  "home-events-more": "عرض الكل",
	  "event-tag-new": "جديد",
	  "event-1-title": "TRPG في Hsinchu",
	  "event-1-desc": "فعالية تقديمية للمبتدئين تقام بشكل منتظم في منطقة Hsinchu، نرحب أيضًا بمحبي TRPG.",
	  "event-register": "سجّل الآن",
	  "event-tag-featured": "مميز",
	  "event-2-title": "فعالية خاصة",
	  "event-2-desc": "هل تحب عالم ⚔️ السيوف والسحر 🔥؟ انضم لتجربة سحر لعبة تقمص الأدوار على الطاولة!",
	  "event-tag-popular": "شائع",
	  "event-3-title": "لعبة لعب الأدوار لزملاء الدراسة",
	  "event-3-desc": "تم إنشاء حدث تشغيل جماعي TRPG فريد من نوعه خصيصًا لجميع الطلاب، مما يسمح برحلة رائعة في عالم الخيال لتخفيف ضغوط الحياة وإحضار الشجاعة لمواجهة العمل المدرسي والمستقبل.",
	  "home-partners": "شركاء",
	  "partners1": "خزينة الأسد العتيق",
	  "partners2": "المستشفى مجنون",
	  "partners3": "فضاء الألغاز",
	  "mission-title": "فلسفتنا",
	  "mission-desc": "من خلال TRPG، نخلق روابط تساعد الأشخاص المعاصرين على استعادة الدافع والأمل في حياتهم.",
	  "mission-1-title": "الاهتمام بالإنسان العصري",
	  "mission-1-desc": "تساعد تجربة TRPG الغامرة في تخفيف ضغوط الدراسة والعمل والحياة، واستعادة إيقاع الحياة.",
	  "mission-2-title": "تنشيط المجتمع",
	  "mission-2-desc": "نسعى إلى تعزيز تفاعل مجتمع اللاعبين من خلال مشاركتهم في فعاليات TRPG والاجتماعات.",
	  "mission-3-title": "الابتكار والتطوير",
	  "mission-3-desc": "بدمج الثقافة والتعليم والأعمال، نقدم للعملاء أنواعًا جديدة من أنشطة TRPG وتجارب فريدة.",
	  "mission-4-title": "تعاون يربح الجميع",
	  "mission-4-desc": "لدعم ثقافة TRPG، نبني شراكات طويلة الأمد مع الشركات والمدارس والمجتمعات لخلق مكاسب مشتركة.",
	  "stats-users": "المستخدمون النشطون",
	  "stats-events": "عدد الفعاليات",
	  "stats-cities": "المدن الشريكة",
	  "stats-satisfaction": "رضا العملاء",
	  "business-title": "أعمالنا الرئيسية",
	  "business-desc": "من تخطيط الفعاليات الحضورية إلى خدمات التعليق الصوتي، نقدم مجموعة من خدمات TRPG وحلول مصممة خصيصًا.",
	  "business-1-title": "تخطيط فعاليات TRPG",
	  "business-1-sub1": "فعاليات للشركات",
	  "business-1-sub1-desc": "باستخدام التفاعل العالي للـTRPG، نعزز التواصل والانتماء بين الموظفين، مما يرفع الروح المعنوية.",
	  "business-1-sub2": "معسكرات مدرسية",
	  "business-1-sub2-desc": "نُدمج المناهج التعليمية مع TRPG في صيغة معسكرات، ليطور الطلاب الخيال والمنطق والمهارات الاجتماعية.",
	  "business-2-title": "التعليق الصوتي للأعمال والإعلانات",
	  "business-2-sub1": "تعليق وسائط الإعلام",
	  "business-2-sub1-desc": "نوفر خدمات تعليق صوتي احترافية للأفلام والمسلسلات والرسوم المتحركة، بما في ذلك الأصوات والسرد.",
	  "business-2-sub2": "تعليق إعلانات تجارية",
	  "business-2-sub2-desc": "نقدم تعليقًا صوتيًا للإعلانات التجارية ومقاطع الفيديو المؤسسية، وفقًا للأسلوب المطلوب.",
	  "business-3-title": "إدارة العلامات التجارية الثقافية",
	  "business-3-sub1": "تصنيع منتجات خاطفة",
	  "business-3-sub1-desc": "نساعد العملاء في إنتاج منتجات للعلامة التجارية، وتصميم استراتيجيات التسويق لها.",
	  "business-3-sub2": "بيع سلع مرخصة رسمية",
	  "business-3-sub2-desc": "نتعاون مع علامات تجارية معروفة لبيع مجموعات مرخصة رسميًا عبر متاجر فعلية وعبر الإنترنت.",
	  "business-4-title": "التعليم والتدريب",
	  "business-4-sub1": "تدريب ميسّري مهنيين",
	  "business-4-sub1-desc": "من خلال محاضرات ودورات وممارسات جماعية، نؤهل ميسّري TRPG محترفين لنشر هذه الظاهرة.",
	  "business-4-sub2": "إرشاد في تأليف السيناريو",
	  "business-4-sub2-desc": "نوفر إرشادًا في تأليف السيناريو لهواة ومحترفي TRPG، لتعميق الحكي وتصميم محتوى تعليمي أو مهني.",
	  "contact-title": "اتصل بنا",
	  "contact-desc": "إذا كانت لديك أي استفسارات أو رغبة في التعاون، لا تتردد بالتواصل معنا.",
	  "contact-info": "معلومات التواصل",
	  "contact-address-title": "العنوان",
	  "contact-address": "حي الشرق، Hsinchu",
	  "contact-email-title": "البريد الإلكتروني",
	  "contact-email": "lionstrpgvault@gmail.com",
	  "contact-hours-title": "ساعات العمل",
	  "contact-hours": "10:00–20:00",
	  "contact-follow": "تابعنا",
	  "contact-link": "انقر الزر أدناه للحصول على أحدث أخبار الفعاليات، وللتعاون التجاري تواصل معنا عبر صفحتنا على فيسبوك.",
	  "footer-company": "شركة فاطكات للثقافة المحدودة",
	  "footer-desc": "نركز في شركتنا على TRPG، ونقدم تنظيم فعاليات للشركات والمدارس، وتعليق صوتي للخدمات السمعية والبصرية، مما يساعد على تخفيف الضغوط وتعزيز التواصل.",
	  "footer-quicklinks": "روابط سريعة",
	  "footer-home": "الرئيسية",
	  "footer-mission": "فلسفتنا",
	  "footer-business": "أعمالنا",
	  "footer-contact": "اتصل بنا",
	  "footer-services": "خدماتنا",
	  "footer-service-1": "تنظيم TRPG",
	  "footer-service-2": "تعليق وسائط",
	  "footer-service-3": "خدمات ثقافية",
	  "footer-service-4": "تدريب وإرشاد",
	  "footer-address": "تنظيم TRPG",
	  "footer-email": "lionstrpgvault@gmail.com",
	  "footer-hours": "10:00–20:00"
	},
	"tr":{
	  "company-name": "ŞişmanTurk Kültür Ltd. Şti.",
	  "nav-home": "Ana Sayfa",
	  "nav-mission": "Vizyonumuz",
	  "nav-business": "Hizmetler",
	  "nav-contact": "İletişim",
	  "hero-title": "ŞişmanTurk Kültür<br>TRPG Deneyim Platformu",
	  "hero-desc": "Fantastik dünyaları keşfet, hayal gücünü özgür bırak, gerçek bağlar oluştur",
	  "hero-btn-1": "Hemen Deneyimle",
	  "hero-btn-2": "Daha Fazla Bilgi",
	  "home-company-title": "Şirket Tanıtımı",
	  "home-company-desc": "ŞişmanTurk Kültür Ltd. Şti., 2025 yılında yoğun yaşam temposuna sahip modern insanlar için stresi hafifletip oyun dünyasında yeniden hayat enerjisi alevlendirmek amacıyla kuruldu.",
	  "home-company-desc2": "Her türlü TRPG temalı etkinlik düzenlemekte uzmanız. Rahat, eğlenceli ve yaratıcı bir ortam yaratarak farklı karakterler ve hikâyeler deneyimlenirken hayatın sunduğu çeşitli olanakları keşfetmeyi sağlıyoruz.",
	  "home-stats-1": "Aktif Kullanıcı",
	  "home-stats-2": "Gerçekleşen Etkinlik",
	  "home-stats-3": "Memnuniyet",
	  "home-events-title": "Son Etkinlikler",
	  "home-events-more": "Tümünü Gör",
	  "event-tag-new": "Yeni",
	  "event-1-title": "TRPG Hsinchu'da",
	  "event-1-desc": "Hsinchu bölgesinde düzenli olarak gerçekleşen başlangıç etkinliği, TRPG tutkunları da davetlidir.",
	  "event-register": "Hemen Kaydol",
	  "event-tag-featured": "Öne Çıkan",
	  "event-2-title": "Özel Etkinlik",
	  "event-2-desc": "⚔️ Kılıç ve sihir dünyasını seviyorsanız 🔥, masa üstü rol yapma oyununun cazibesini deneyimlemeye davetlisiniz!",
	  "event-tag-popular": "Popüler",
	  "event-3-title": "Sınıf arkadaşlarının TRPG'si",
	  "event-3-desc": "Tüm öğrencilere özel olarak oluşturulan benzersiz bir TRPG grup koşu etkinliği, hayal dünyasında harika bir yolculuğa çıkmanızı sağlayarak hayatın baskısını hafifletiyor ve size okul çalışmaları ve gelecekle yüzleşmek için cesaret veriyor.",
	  "home-partners": "İş Ortakları",
	  "partners1": "Eski Aslan Hazinesi",
	  "partners2": "Hastane çılgın",
	  "partners3": "Bulmaca Mekânı",
	  "mission-title": "Vizyonumuz",
	  "mission-desc": "TRPG aracılığıyla bağlar kurarak modern insanların yaşama olan motivasyonunu ve düşlerini yeniden kazanmalarına yardım ediyoruz.",
	  "mission-1-title": "Modern İnsana Duyarlılık",
	  "mission-1-desc": "Yoğun TRPG deneyimi, eğitim, iş ve hayatın getirdiği baskıyı hafifletmeye yardımcı olarak yaşam ritmini yeniden kazandırır.",
	  "mission-2-title": "Topluluğu Canlandırma",
	  "mission-2-desc": "Oyun tutkunlarının TRPG aracılığıyla etkinliklere katılarak insanlarla iletişimini güçlendirmelerini hedefliyoruz.",
	  "mission-3-title": "Yenilikçi Gelişim",
	  "mission-3-desc": "Kültür, eğitim ve işletmeyi harmanlayarak müşterilere yeni TRPG deneyim biçimleri ve eşsiz deneyimler sunuyoruz.",
	  "mission-4-title": "Ortak Kazanım",
	  "mission-4-desc": "TRPG kültürünün gelişmesi için şirketler, okullar ve topluluklarla uzun vadeli iş birliği kurarak çok yönlü kazanç hedefliyoruz.",
	  "stats-users": "Aktif Kullanıcı",
	  "stats-events": "Gerçekleşen Etkinlik",
	  "stats-cities": "Ortak Şehirler",
	  "stats-satisfaction": "Müşteri Memnuniyeti",
	  "business-title": "Hizmet Alanları",
	  "business-desc": "Yüz yüze etkinlik planlamasından görsel-işitsel seslendirme hizmetlerine kadar, TRPG temalı çoklu hizmetler ve özelleştirilmiş çözümler sunuyoruz.",
	  "business-1-title": "TRPG Etkinlik Planlaması",
	  "business-1-sub1": "Kurumsal Etkinlikler",
	  "business-1-sub1-desc": "TRPG’nin yüksek etkileşimini kullanarak iletişim ve ekip ruhunu güçlendiriyor, çalışan moralini yükseltiyoruz.",
	  "business-1-sub2": "Okul Kampları",
	  "business-1-sub2-desc": "Eğitim müfredatını TRPG ile kamp formatında birleştirerek öğrencilerin hayal gücü, mantık ve sosyal becerilerini geliştiriyoruz.",
	  "business-2-title": "Görsel‑İşitsel Dublaj",
	  "business-2-sub1": "Medya Dublajı",
	  "business-2-sub1-desc": "Film, dizi, animasyon gibi medya içeriklerine karakter ve anlatıcı sesiyle profesyonel dublaj sağlıyoruz.",
	  "business-2-sub2": "Reklam Dublajı",
	  "business-2-sub2-desc": "Kurumsal reklamlar, ürün tanıtımları, tanıtım filmleri için tarz ve ihtiyaca uygun seslendirme sunuyoruz.",
	  "business-3-title": "Kültürel Marka Yönetimi",
	  "business-3-sub1": "Telifli Ürün Tasarımı",
	  "business-3-sub1-desc": "Müşteriler için marka yan ürünleri üretip pazarlama stratejileri tasarlıyoruz.",
	  "business-3-sub2": "Resmi Ürün Satışı",
	  "business-3-sub2-desc": "Ünlü IP’lerle iş birliği içinde resmi lisanslı setleri çevrimiçi ve mağazada satıyoruz.",
	  "business-4-title": "Eğitim ve Danışmanlık",
	  "business-4-sub1": "Profesyonel Oyun Yöneticisi Eğitimi",
	  "business-4-sub1-desc": "Konuşmalar, kurslar ve grup stajlarıyla profesyonel TRPG yöneticileri yetiştiriyoruz.",
	  "business-4-sub2": "Senaryo Yazım Danışmanlığı",
	  "business-4-sub2-desc": "TRPG meraklıları ve profesyonellerine senaryo yazım danışmanlığı sunarak hikayeyi derinleştiriyor ve eğitim ya da sektörel taleplere uygun içerik tasarlıyoruz.",
	  "contact-title": "İletişim",
	  "contact-desc": "Herhangi bir sorunuz veya iş birliği isteğiniz olursa bizimle iletişime geçebilirsiniz.",
	  "contact-info": "İletişim Bilgileri",
	  "contact-address-title": "Adres",
	  "contact-address": "Doğu Bölgesi, Hsinchu",
	  "contact-email-title": "E‑posta",
	  "contact-email": "lionstrpgvault@gmail.com",
	  "contact-hours-title": "Çalışma Saatleri",
	  "contact-hours": "10:00–20:00",
	  "contact-follow": "Bizi Takip Et",
	  "contact-link": "Etkinlik haberleri için aşağıdaki butona tıklayın; iş birliği için FB sayfamızdan ulaşabilirsiniz.",
	  "footer-company": "ŞişmanTurk Kültür Ltd. Şti.",
	  "footer-desc": "Şirketimiz TRPG odaklıdır ve kurumsal ve okul etkinlikleri, seslendirme gibi çeşitli hizmetler sunar; modern insanların stresini azaltmaya ve etkileşimi artırmaya yardımcı olur.",
	  "footer-quicklinks": "Hızlı Bağlantılar",
	  "footer-home": "Ana Sayfa",
	  "footer-mission": "Vizyonumuz",
	  "footer-business": "Hizmetler",
	  "footer-contact": "İletişim",
	  "footer-services": "Hizmetlerimiz",
	  "footer-service-1": "TRPG Etkinlik Planlama",
	  "footer-service-2": "Dublaj ve Reklam",
	  "footer-service-3": "Kültürel Deneyimler",
	  "footer-service-4": "Eğitim ve Danışmanlık",
	  "footer-address": "TRPG Etkinlik Planlama",
	  "footer-email": "lionstrpgvault@gmail.com",
	  "footer-hours": "10:00–20:00"
	}
};


